### ISSUE TITLE
Requirements not in setup.py

### ISSUE THREAD

**Issue by Vieler** [nelsond/thorlabs-mtd415t#5]
Currently, the `pyserial` requirement live in a separate file, when it should be listed in the `install_requires` field of the setup function. If you try to install this package in a new environment, an error is raised because `pyserial` cannot be found. Adding it to the `install_requires` list should solve the problem.

**Comment by nelsond** [comment]
Thank you for pointing this out. This should be fixed now, see

https://github.com/nelsond/thorlabs-mtd415t/blob/715eb2b3203a0e67d0a6b4a9d3f883031ceccaf9/setup.py#L44
